# Generated by Django 5.0.4 on 2024-11-10 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del examen')),
                ('descripcion', models.TextField(verbose_name='Descripción del examen')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        migrations.CreateModel(
            name='ExamenRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de realización')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='imat.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Examen Respuesta',
                'verbose_name_plural': 'Exámenes Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto de la pregunta')),
                ('texto_ayuda', models.TextField(blank=True, verbose_name='Texto de ayuda')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='imat.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('anio_residencia', models.CharField(choices=[('primer', 'Primer Año'), ('segundo', 'Segundo Año'), ('tercer', 'Tercer Año'), ('cuarto', 'Cuarto Año')], default='primer', help_text='Seleccione a que año pertenecés en la residencia', max_length=20, verbose_name='Año de residencia')),
                ('examenes', models.ManyToManyField(related_name='residentes', through='imat.ExamenRespuesta', to='imat.examen')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.AddField(
            model_name='examenrespuesta',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_respuestas', to='imat.residente', verbose_name='Residente'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la respuesta')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('examen_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='imat.examenrespuesta', verbose_name='Examen Respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='imat.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
