# Generated by Django 5.0.4 on 2024-11-18 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residente',
            name='examenes',
        ),
        migrations.AddField(
            model_name='examenrespuesta',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios del docente'),
        ),
        migrations.AddField(
            model_name='examenrespuesta',
            name='nivel',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('intermedio', 'Intermedio'), ('bajo', 'Bajo')], max_length=20, null=True, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='examenrespuesta',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='anio_residencia',
            field=models.CharField(choices=[('primer', 'Primer Año'), ('segundo', 'Segundo Año'), ('tercer', 'Tercer Año'), ('cuarto', 'Cuarto Año')], default='primer', help_text='Seleccione a qué año pertenece en la residencia', max_length=20, verbose_name='Año de residencia'),
        ),
        migrations.CreateModel(
            name='EvaluacionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de evaluación')),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje')),
                ('nivel', models.CharField(choices=[('alto', 'Alto'), ('intermedio', 'Intermedio'), ('bajo', 'Bajo')], max_length=20, verbose_name='Nivel')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios del docente')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_practicas', to='imat.residente', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Evaluación Práctica',
                'verbose_name_plural': 'Evaluaciones Prácticas',
            },
        ),
        migrations.CreateModel(
            name='ProgresoResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_teorico_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje Teórico Total')),
                ('puntaje_practico_total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje Práctico Total')),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='imat.residente', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Progreso del Residente',
                'verbose_name_plural': 'Progresos de los Residentes',
            },
        ),
    ]
