# Generated by Django 5.0.4 on 2024-10-28 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imat', '0002_alter_examen_options_alter_pregunta_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='residente',
        ),
        migrations.CreateModel(
            name='ExamenRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de realización')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='imat.examen', verbose_name='Examen')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='imat.residente', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Examen Respuesta',
                'verbose_name_plural': 'Exámenes Respuestas',
            },
        ),
        migrations.AddField(
            model_name='respuesta',
            name='examen_respuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='imat.examenrespuesta', verbose_name='Examen Respuesta'),
        ),
    ]
