# Generated by Django 5.0.4 on 2024-10-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imat', '0003_remove_respuesta_residente_examenrespuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='examenes',
            field=models.ManyToManyField(related_name='residentes', through='imat.ExamenRespuesta', to='imat.examen'),
        ),
        migrations.AlterField(
            model_name='examenrespuesta',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_respuestas', to='imat.residente', verbose_name='Residente'),
        ),
    ]
