# Generated by Django 5.0.4 on 2024-11-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imat', '0004_residente_examenes_alter_examenrespuesta_residente'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='anio_residencia',
            field=models.CharField(choices=[('primer', 'Primer Año'), ('segundo', 'Segundo Año'), ('tercer', 'Tercer Año'), ('cuarto', 'Cuarto Año')], default='primer', help_text='Seleccioná a que año pertenecés en la residencia', max_length=20, verbose_name='Año de Residencia'),
        ),
    ]
