# Generated by Django 5.0.4 on 2024-07-27 03:35

import casos_interesantes_db.models
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0002_especialidad_organo_region_sistema_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la patología')),
            ],
            options={
                'verbose_name': 'Patología',
                'verbose_name_plural': 'Patologías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='casointeresante',
            name='Hallazgos',
            field=models.TextField(default='', help_text='Ingrese los hallazgos encontrados en el estudio.', verbose_name='Hallazgos'),
        ),
        migrations.AlterField(
            model_name='casointeresante',
            name='etiquetas',
            field=taggit.managers.TaggableManager(blank=True, help_text='Puede agregar etiquetas para facilitar la búsqueda de este caso. Separe las etiquetas con comas. Por ejemplo: neumonía, COVID-19, pulmón.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
