# Generated by Django 5.0.4 on 2024-08-15 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0005_alter_casointeresante_hallazgos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCasoInteresante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='casos_interesantes/', verbose_name='Imagen del caso')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='casos_interesantes_db.casointeresante')),
            ],
        ),
    ]
