# Generated by Django 5.0.4 on 2024-08-24 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0006_imagencasointeresante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='hallazgos',
            field=models.ForeignKey(help_text='Ingrese el nombre del hallazgo principal del caso. Por ejemplo: neumonía atípica, tumor de Wilms, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='casos_interesantes', to='casos_interesantes_db.patologia', verbose_name='Hallazgos'),
        ),
        migrations.AlterField(
            model_name='imagencasointeresante',
            name='imagen',
            field=models.ImageField(help_text='Cargo una o más imágenes relacionadas con el caso.', upload_to='casos_interesantes/', verbose_name='Imagen del caso'),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la patología'),
        ),
    ]
