# Generated by Django 5.0.4 on 2024-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0007_alter_casointeresante_hallazgos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='contraste_ev',
            field=models.BooleanField(default=False, help_text='Seleccione si se utilizó contraste endovenoso en el estudio.', verbose_name='Contraste endovenoso'),
        ),
        migrations.AlterField(
            model_name='casointeresante',
            name='contraste_or',
            field=models.BooleanField(default=False, help_text='Seleccione si se utilizó contraste oral en el estudio.', verbose_name='Contraste oral'),
        ),
        migrations.AlterField(
            model_name='imagencasointeresante',
            name='imagen',
            field=models.ImageField(help_text='Cargue una o más imágenes relacionadas con el caso.', upload_to='casos_interesantes/', verbose_name='Imagen del caso'),
        ),
    ]
