# Generated by Django 5.0.4 on 2024-08-26 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0008_alter_casointeresante_contraste_ev_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casointeresante',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_interesantes', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
