# Generated by Django 5.0.4 on 2024-09-10 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0010_alter_casointeresante_hallazgos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='especialidad',
            field=models.ForeignKey(help_text='Selecciona a qué subespecialidad pertenece el caso.', on_delete=django.db.models.deletion.CASCADE, related_name='casos_interesantes', to='casos_interesantes_db.especialidad'),
        ),
        migrations.AlterField(
            model_name='casointeresante',
            name='id_estudio',
            field=models.CharField(error_messages={'unique': 'El ID de estudio ingresado ya existe en la base de datos.'}, help_text='Cada estudio cuenta con un ID único que lo identifica y es asignado por cada equipo. Ingresando este ID se evitará duplicados.', max_length=50, unique=True, verbose_name='ID de estudio'),
        ),
    ]
