# Generated by Django 5.0.4 on 2024-09-12 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0011_alter_casointeresante_especialidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casointeresante',
            name='usuario_carga',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='casos_interesantes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cargó el caso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(error_messages={'unique': 'El DNI ingresado ya existe en la base de datos.'}, help_text='Ingrese el DNI sin puntos.', max_length=8, unique=True, verbose_name='DNI del paciente'),
        ),
    ]
