# Generated by Django 5.0.4 on 2024-09-21 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0013_alter_casointeresante_usuario_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='contraste_ev',
            field=models.BooleanField(default=False, help_text='¿Se utilizó contraste endovenoso en el estudio?', verbose_name='Contraste endovenoso'),
        ),
        migrations.AlterField(
            model_name='casointeresante',
            name='id_estudio',
            field=models.CharField(error_messages={'unique': 'El ID de estudio ingresado ya existe en la base de datos.'}, help_text='Cada estudio cuenta con un ID único que lo identifica y es asignado por cada equipo. Ingresando este ID se evitará duplicados.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_id_estudio', message='El ID de estudio debe contener solo números y guiones.', regex='^\\d+(-\\d+)*$')], verbose_name='ID de estudio'),
        ),
    ]
