# Generated by Django 5.0.4 on 2024-09-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0014_alter_casointeresante_contraste_ev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='id_estudio',
            field=models.CharField(error_messages={'unique': 'El ID de estudio ingresado ya existe en la base de datos.'}, help_text='Cada estudio cuenta con un ID único que lo identifica y es asignado por cada equipo. Ingresando este ID se evitará duplicados.', max_length=50, unique=True, verbose_name='ID de estudio'),
        ),
    ]
