# Generated by Django 5.0.4 on 2024-09-24 16:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0015_alter_casointeresante_id_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casointeresante',
            name='id_estudio',
            field=models.CharField(error_messages={'unique': 'El ID de estudio ingresado ya existe en la base de datos.'}, help_text='Cada estudio cuenta con un ID o número de acceso únicos que lo identifica y es asignado por cada equipo. Ingresando este ID se evitará duplicados. Si el ID del estudio tiene caracteres especiales, deben ser eliminados para que sea un número entero. Por ejemplo, 1234-567 debe convertirse en 1234567.', max_length=50, unique=True, verbose_name='ID de estudio'),
        ),
        migrations.AlterField(
            model_name='imagencasointeresante',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
