# Generated by Django 5.0.4 on 2024-09-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0016_alter_casointeresante_id_estudio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casointeresante',
            old_name='fregmento_informe',
            new_name='fragmento_informe',
        ),
        migrations.AlterField(
            model_name='casointeresante',
            name='id_estudio',
            field=models.CharField(error_messages={'unique': 'El ID de estudio ingresado ya existe en la base de datos.'}, help_text='Cada caso debe contar con un ID único para evitar duplicados en la base de datos. El ID debe formarse tomando la fecha del estudio y la hora. Por ejemplo: para la fecha 12/05/2021 y la hora 14:30, el ID sería 120520211430.', max_length=50, unique=True, verbose_name='ID de estudio'),
        ),
    ]
