# Generated by Django 5.0.4 on 2024-09-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0017_rename_fregmento_informe_casointeresante_fragmento_informe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='casointeresante',
            name='tipo_estudio',
        ),
        migrations.AddField(
            model_name='casointeresante',
            name='tipo_estudio',
            field=models.ManyToManyField(help_text='Seleccione el método principal del caso. Puede seleccionar más de uno si corresponde.', to='casos_interesantes_db.tipoestudio'),
        ),
    ]
