# Generated by Django 5.0.4 on 2024-09-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0018_tipoestudio_remove_casointeresante_tipo_estudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoestudio',
            name='codigo',
        ),
    ]
