# Generated by Django 5.0.4 on 2024-10-06 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos_interesantes_db', '0019_remove_tipoestudio_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casointeresante',
            name='contraste_ev',
        ),
        migrations.RemoveField(
            model_name='casointeresante',
            name='contraste_or',
        ),
        migrations.RemoveField(
            model_name='casointeresante',
            name='tipo_estudio',
        ),
        migrations.CreateModel(
            name='MetodoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraste_ev', models.BooleanField(default=False, verbose_name='Contraste endovenoso')),
                ('contraste_or', models.BooleanField(default=False, verbose_name='Contraste oral')),
                ('contraste_gadolineo', models.BooleanField(default=False, verbose_name='Contraste con gadolinio')),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos_interesantes_db.tipoestudio')),
            ],
        ),
        migrations.AddField(
            model_name='casointeresante',
            name='metodos_estudio',
            field=models.ManyToManyField(help_text='Seleccione el método principal de estudio utilizado para el caso. Puede seleccionar más de uno si corresponde.', to='casos_interesantes_db.metodoestudio'),
        ),
    ]
