# Generated by Django 5.0.4 on 2024-10-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='facturacion',
            options={'ordering': ['fecha_facturacion'], 'verbose_name': 'Facturación', 'verbose_name_plural': 'Facturaciones'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='pacienteregion',
            options={'ordering': ['fecha'], 'verbose_name': 'Paciente por región', 'verbose_name_plural': 'Pacientes por región'},
        ),
        migrations.AlterModelOptions(
            name='regionecografia',
            options={'ordering': ['nombre'], 'verbose_name': 'Región de ecografía', 'verbose_name_plural': 'Regiones de ecografía'},
        ),
        migrations.AlterModelOptions(
            name='valorregionempresa',
            options={'verbose_name': 'Valor por región y empresa', 'verbose_name_plural': 'Valores por región y empresa'},
        ),
        migrations.RenameField(
            model_name='facturacion',
            old_name='fecha',
            new_name='fecha_facturacion',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cantidad_regiones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='mes_facturacion',
            field=models.CharField(default='2024-10', editable=False, max_length=7),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='paciente_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.pacienteregion'),
        ),
        migrations.AddField(
            model_name='pacienteregion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.empresa'),
        ),
    ]
