# Generated by Django 5.0.4 on 2024-10-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_empresa_options_alter_facturacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacienteregion',
            options={'ordering': ['fecha'], 'verbose_name': 'Regiones por paciente', 'verbose_name_plural': 'Regiones por pacientes'},
        ),
        migrations.RemoveField(
            model_name='pacienteregion',
            name='region_ecografia',
        ),
        migrations.AddField(
            model_name='pacienteregion',
            name='regiones',
            field=models.ManyToManyField(to='facturacion.regionecografia'),
        ),
    ]
