# Generated by Django 5.0.4 on 2024-10-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_pacienteregion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='valor_region_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.valorregionempresa'),
        ),
        migrations.CreateModel(
            name='EstudioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.empresa')),
                ('region_ecografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.regionecografia')),
            ],
            options={
                'verbose_name': 'Estudio Especial',
                'verbose_name_plural': 'Estudios Especiales',
                'unique_together': {('empresa', 'region_ecografia', 'descripcion')},
            },
        ),
        migrations.AddField(
            model_name='facturacion',
            name='estudio_especial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.estudioespecial'),
        ),
    ]
