# Generated by Django 5.0.4 on 2024-10-24 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_facturacion_valor_region_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteregion',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
