# Generated by Django 5.0.4 on 2024-11-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_pacienteregion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='mes_facturacion',
            field=models.CharField(default='2024-11', editable=False, max_length=7),
        ),
    ]
