# Generated by Django 5.0.4 on 2024-06-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposResidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencia', models.CharField(choices=[('DM', 'Diagnóstico Médico'), ('IM', 'Investigaciones Médicas'), ('FV', 'Fundación Favaloro'), ('US', 'Universidad del Salvador')], max_length=20, verbose_name='Residencia')),
                ('año', models.CharField(choices=[('R1', 'Primer año'), ('R2', 'Segundo año'), ('R3', 'Tercer año'), ('R4', 'Cuarto año')], max_length=20, verbose_name='Año')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.residente')),
            ],
            options={
                'verbose_name': 'Residentes por año',
                'verbose_name_plural': 'Grupos de residentes por año',
            },
        ),
    ]
