# Generated by Django 5.0.3 on 2024-03-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
