# Generated by Django 5.0.4 on 2024-05-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
