# Generated by Django 5.0.4 on 2024-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_administrativo_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='telefono',
            field=models.CharField(default=0, max_length=10, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
