# Generated by Django 5.0.3 on 2024-03-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0002_delete_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fecha_de_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('matricula', models.CharField(max_length=6, unique=True)),
                ('fecha_de_ingreso', models.DateField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
