# Generated by Django 5.0.3 on 2024-03-16 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Residente',
        ),
    ]
