# Generated by Django 5.0.4 on 2024-06-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_gruposresidentes_options_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='nombre_aula',
            field=models.CharField(choices=[('DM', 'Diagnóstico Médico'), ('IM', 'Investigaciones Médicas')], max_length=50, verbose_name='Nombre del aula'),
        ),
        migrations.AlterField(
            model_name='gruposresidentes',
            name='año',
            field=models.CharField(choices=[('R1', 'Primer año'), ('R2', 'Segundo año'), ('R3', 'Tercer año'), ('R4', 'Cuarto año')], help_text='Seleccione el año en el que se encuentra el residente', max_length=20, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='gruposresidentes',
            name='residencia',
            field=models.CharField(choices=[('DM', 'Diagnóstico Médico'), ('IM', 'Investigaciones Médicas'), ('FV', 'Fundación Favaloro'), ('US', 'Universidad del Salvador')], help_text='Seleccione la residencia a la que pertenece el residente', max_length=20, verbose_name='Residencia'),
        ),
        migrations.AlterField(
            model_name='gruposresidentes',
            name='residente',
            field=models.ForeignKey(help_text='Seleccione al residente que quiere asignar a un grupo', on_delete=django.db.models.deletion.CASCADE, to='asistencia.residente'),
        ),
    ]
