# Generated by Django 5.0.4 on 2024-06-26 01:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_aulas_nombre_aula_alter_gruposresidentes_año_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPeriodica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto_positivo', models.TextField(blank=True, max_length=600, verbose_name='Aspecto positivo')),
                ('aspecto_negativo', models.TextField(blank=True, max_length=600, verbose_name='Aspecto negativo')),
                ('nota', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Nota')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Evaluador')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.residente', verbose_name='Residente')),
            ],
            options={
                'verbose_name': 'Evaluación periódica',
                'verbose_name_plural': 'Evaluaciones periódicas',
            },
        ),
    ]
