# Generated by Django 5.0.3 on 2024-04-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='llegada_tarde',
            field=models.BooleanField(default=False, verbose_name='¿Llegó tarde?'),
        ),
    ]
