# Generated by Django 5.0.4 on 2024-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_evaluacionperiodica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasesVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('vimeo_url', models.URLField(verbose_name='URL de Vimeo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='evaluacionperiodica',
            unique_together={('residente', 'evaluador', 'fecha')},
        ),
    ]
