# Generated by Django 5.0.3 on 2024-04-03 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_registroasistencia_llegada_tarde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
    ]
