# Generated by Django 5.0.3 on 2024-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residente',
            options={'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        migrations.AlterField(
            model_name='residente',
            name='dni',
            field=models.CharField(max_length=8, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='fecha_de_ingreso',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='matricula',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
