# Generated by Django 5.0.4 on 2024-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_sedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
    ]
