# Generated by Django 5.0.4 on 2024-05-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_sedes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='direccion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='nombre_sede',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
    ]
