# Generated by Django 5.0.4 on 2024-07-13 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_clasesvideos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('A', 'Abdomen'), ('CV', 'Cardiovascular'), ('MSK', 'Musculoesquelético'), ('N', 'Neuroradiología'), ('O', 'Obstetricia'), ('IP', 'Imágenes pediátricas'), ('UR', 'Uroradiología y genitales masculinos'), ('IM', 'Imágenes mamarias'), ('CC', 'Cabeza y cuello'), ('T', 'Tórax'), ('OR', 'Oncoloradiología'), ('IR', 'Intervencionismo'), ('N', 'Nuclear'), ('GIN', 'Ginecología'), ('OT', 'Otras temáticas')], error_messages={'unique': 'Esa sección ya está registrada.'}, max_length=20, unique=True, verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Clasificación temática',
                'verbose_name_plural': 'Clasificaciones temáticas',
            },
        ),
        migrations.CreateModel(
            name='DisertantesClases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disertante', models.CharField(max_length=100, verbose_name='Nombre del disertante')),
                ('apellido_disertante', models.CharField(max_length=100, verbose_name='Apellido del disertante')),
            ],
            options={
                'verbose_name': 'Disertante',
                'verbose_name_plural': 'Disertantes',
            },
        ),
        migrations.AlterModelOptions(
            name='clasesvideos',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Videos de clases'},
        ),
        migrations.AddField(
            model_name='clasesvideos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='clasesvideos',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='clasesvideos',
            name='clasificaciones_tematicas',
            field=models.ManyToManyField(related_name='videos', to='asistencia.clasificaciontematica'),
        ),
        migrations.AddField(
            model_name='clasesvideos',
            name='disertante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='asistencia.disertantesclases'),
        ),
    ]
