# Generated by Django 5.0.4 on 2024-05-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_sedes_direccion_alter_sedes_nombre_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='direccion',
            field=models.CharField(error_messages={'unique': 'Ya existe una sede registrada con esa dirección.'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='nombre_sede',
            field=models.CharField(error_messages={'unique': 'Esa sede ya está registrada.'}, max_length=100, unique=True),
        ),
    ]
