# Generated by Django 5.0.3 on 2024-04-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_remove_registroasistencia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='llegada_a_tiempo',
            field=models.BooleanField(default=True, verbose_name='¿Llegó a tiempo?'),
        ),
    ]
