# Generated by Django 5.0.4 on 2024-07-15 18:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_clasificaciontematica_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteoVisitaPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de visita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo de visita',
                'verbose_name_plural': 'Conteo de visitas',
            },
        ),
        migrations.CreateModel(
            name='ConteoVisualizacionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de visualización')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.clasesvideos')),
            ],
            options={
                'verbose_name': 'Conteo de visualización',
                'verbose_name_plural': 'Conteo de visualizaciones',
            },
        ),
    ]
