# Generated by Django 5.0.4 on 2024-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_conteovisitapagina_conteovisualizacionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificaciontematica',
            name='seccion',
            field=models.CharField(choices=[('A', 'Abdomen'), ('CV', 'Cardiovascular'), ('MSK', 'Musculoesquelético'), ('NR', 'Neuroradiología'), ('O', 'Obstetricia'), ('IP', 'Imágenes pediátricas'), ('UR', 'Uroradiología y genitales masculinos'), ('IM', 'Imágenes mamarias'), ('CC', 'Cabeza y cuello'), ('T', 'Tórax'), ('OR', 'Oncoimágenes'), ('IR', 'Intervencionismo'), ('NU', 'Nuclear'), ('GIN', 'Ginecología'), ('OT', 'Otras')], error_messages={'unique': 'Esa sección ya está registrada.'}, max_length=20, unique=True, verbose_name='Sección'),
        ),
    ]
