# Generated by Django 5.0.4 on 2024-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0013_ateneoevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ateneoevaluacion',
            options={'verbose_name': 'Evaluación de ateneo', 'verbose_name_plural': 'Evaluaciones de ateneo'},
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='claridad_presentacion_oral',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué tan clara fue la presentación oral?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='comentario_aprendizaje',
            field=models.TextField(help_text='Comenta brevemente que aprendiste con la presentación.', max_length=600),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='cumplimiento_objetivos',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Que tanto se cumplieron los objetivos de aprendizaje?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='importancia_tema',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué tan importante te resultó el tema propuesto?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='nota_general',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué nota general le darias a la presentación?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='puntaje_bibliografia',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué puntaje le darias al tipo de bibliografía elegida?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='puntaje_calidad_presentacion',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué puntaje le darias a la presentación,  teniendo en cuenta la calidad del contenido y la forma de presentación?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='puntaje_calidad_texto',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué puntaje le darias a la calidad del texto de la presentación,  teniendo en cuenta la claridad de la informacion y la ortografía?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='puntaje_contenido_cientifico',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Qué puntaje le darias a la presentación,  teniendo en cuenta el contenido cientifico de la misma?'),
        ),
        migrations.AlterField(
            model_name='ateneoevaluacion',
            name='uso_tiempo',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='¿Como calificaría el uso del tiempo en la presentación?'),
        ),
    ]
