# Generated by Django 5.0.4 on 2024-10-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0015_usuario_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='image',
        ),
    ]
