# Generated by Django 5.0.3 on 2024-03-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'verbose_name_plural': 'Opciones'},
        ),
    ]
